import { useState, useEffect } from "react";
import type { AstroEvent } from "@workspace/api-client-react";
import { ExternalLink } from "lucide-react";

interface Props { event: AstroEvent; }

/**
 * TODO: move to @workspace/api-client-react once /events/:id/colibri/followup
 * is added to the OpenAPI spec and the client is regenerated. Defined locally
 * for now rather than importing across the workspace boundary from the
 * api-server, which the frontend does not depend on.
 */
interface ColibriReport {
  reportId: string;
  reportUrl: string;
  subject: string;
  observatory: string;
  instrument: string;
  observationCategory: string;
  reportedResults: string;
  authors: string;
  contacts: string;
  redshift: number | null;
  hasOpticalFollowup: boolean;
  hasPhotometry: boolean;
  parsedAt: string;
  /** LLM-generated by Astro-COLIBRI — never render without its provenance label. */
  aiSummary: string | null;
  aiModel: string | null;
}

interface ColibriFollowup {
  available: boolean;
  figureUrl: string | null;
  reports: ColibriReport[];
  contacts: Array<{ name: string; email: string }>;
  reportCount: number;
}

/** Cards rendered inline; the rest stay one click away on Astro-COLIBRI. */
const MAX_CARDS = 10;

/**
 * Contacts shown before collapsing to a count. Astro-COLIBRI returned 137 for
 * a single GRB — every address parsed out of every circular's FROM header.
 * Listing them all would turn a science panel into a mailing list.
 */
const MAX_CONTACTS = 8;

export function FollowupReports({ event }: Props) {
  const [data, setData] = useState<ColibriFollowup | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  // Our own API is addressed by the database id; the api-server translates it
  // to the event name before querying Astro-COLIBRI.
  useEffect(() => {
    const controller = new AbortController();

    setLoading(true);
    setError(false);
    setData(null);

    fetch(`/api/events/${event.id}/colibri/followup`, { signal: controller.signal })
      .then(async (res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return (await res.json()) as ColibriFollowup;
      })
      .then((payload) => {
        setData(payload);
        setLoading(false);
      })
      .catch((err: Error) => {
        // An aborted request is a tab switch, not a failure — the component is
        // unmounting and must not set state.
        if (err.name === "AbortError") return;
        setError(true);
        setLoading(false);
      });

    return () => controller.abort();
  }, [event.id]);

  const reports = data?.reports ?? [];
  const shown = reports.slice(0, MAX_CARDS);
  const hiddenCount = reports.length - shown.length;
  const colibriHref = `https://astro-colibri.science/sources/${encodeURIComponent(event.eventId)}`;

  return (
    <div className="flex flex-col h-full p-3 gap-4 overflow-y-auto scrollbar-thin">
      {/* ── Follow-up overview ──────────────────────────────────────────── */}
      <div>
        <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1.5">
          Follow-up overview · Astro-COLIBRI
        </div>

        {loading && <div className="h-40 w-full rounded bg-muted/30 animate-pulse" />}

        {!loading && error && (
          <div className="text-[11px] text-muted-foreground">
            Astro-COLIBRI follow-up data unavailable
          </div>
        )}

        {!loading && !error && data?.available && data.figureUrl && (
          <img
            src={data.figureUrl}
            alt={`Follow-up overview for ${event.eventId}`}
            className="w-full rounded object-contain max-h-56"
          />
        )}

        {!loading && !error && data && !data.available && (
          <div className="text-[11px] text-muted-foreground">
            No follow-up summary in Astro-COLIBRI for this event
          </div>
        )}

        {!loading && (
          <a
            href={colibriHref}
            target="_blank"
            rel="noopener noreferrer"
            className="mt-1 inline-flex items-center gap-1 text-[10px] text-muted-foreground hover:text-primary transition-colors no-underline"
          >
            Astro-COLIBRI
            <ExternalLink className="w-3 h-3" />
          </a>
        )}
      </div>

      {/* ── Contacts ────────────────────────────────────────────────────── */}
      {!loading && !error && (data?.contacts?.length ?? 0) > 0 && (
        <div>
          <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1.5">
            Contacts
          </div>
          <div className="flex flex-col gap-0.5">
            {data!.contacts.slice(0, MAX_CONTACTS).map((c, i) => (
              <div key={`${c.email}-${i}`} className="flex items-baseline gap-1.5 text-[11px]">
                <span className="text-foreground">{c.name || "Unnamed"}</span>
                {c.email && (
                  <a
                    href={`mailto:${c.email}`}
                    className="text-[10px] text-muted-foreground hover:text-primary transition-colors"
                  >
                    {c.email}
                  </a>
                )}
              </div>
            ))}
            {data!.contacts.length > MAX_CONTACTS && (
              <div className="text-[10px] text-muted-foreground">
                and {data!.contacts.length - MAX_CONTACTS} more
              </div>
            )}
          </div>
          <div className="mt-1 text-[10px] text-muted-foreground italic">
            Source: Astro-COLIBRI GCN circular parsing
          </div>
        </div>
      )}

      {/* ── Report cards ────────────────────────────────────────────────── */}
      {!loading && !error && reports.length > 0 && (
        <div>
          <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1.5">
            Follow-up reports ({data?.reportCount ?? reports.length})
          </div>
          <div className="flex flex-col gap-2">
            {shown.map((r, i) => (
              <div
                key={r.reportId || i}
                className="flex flex-col gap-1.5 rounded border border-border bg-card p-2.5 text-[11px]"
              >
                <div className="text-foreground font-medium truncate" title={r.subject}>
                  {r.subject}
                </div>

                {(r.observatory || r.observationCategory) && (
                  <div className="flex flex-wrap items-center gap-1">
                    {r.observatory && (
                      <span className="bg-accent/30 rounded px-1.5 py-0.5 text-[10px]">
                        {r.observatory}
                      </span>
                    )}
                    {r.observationCategory && (
                      <span className="bg-accent/30 rounded px-1.5 py-0.5 text-[10px]">
                        {r.observationCategory}
                      </span>
                    )}
                  </div>
                )}

                {r.instrument && (
                  <div className="text-muted-foreground">{r.instrument}</div>
                )}

                {/* Measured findings, reported by the circular's authors. Upstream
                    sends these as separate statements joined with newlines, so
                    whitespace-pre-line keeps each one on its own line. */}
                {r.reportedResults && (
                  <div className="text-foreground whitespace-pre-line">{r.reportedResults}</div>
                )}

                {r.redshift !== null && (
                  <div className="text-muted-foreground">z = {r.redshift.toFixed(4)}</div>
                )}

                {/* Subordinate to the measured values above: dashed, muted,
                    italic, and never shown without saying who wrote it. */}
                {r.aiSummary && (
                  <div className="mt-1 rounded border border-dashed border-border p-1.5">
                    <div className="mb-0.5 text-[9px] font-mono text-muted-foreground uppercase tracking-wider">
                      AI summary · Astro-COLIBRI{r.aiModel ? ` · ${r.aiModel}` : ""}
                    </div>
                    <div className="text-[10px] text-muted-foreground italic">{r.aiSummary}</div>
                  </div>
                )}

                <div className="flex items-center justify-between gap-2">
                  <span className="text-[10px] text-muted-foreground">{r.parsedAt}</span>
                  {r.reportUrl && (
                    <a
                      href={r.reportUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-muted-foreground hover:text-primary transition-colors"
                      aria-label={`Open report ${r.reportId || ""} at source`}
                    >
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  )}
                </div>
              </div>
            ))}
          </div>

          {hiddenCount > 0 && (
            <a
              href={colibriHref}
              target="_blank"
              rel="noopener noreferrer"
              className="mt-1.5 inline-flex items-center gap-1 text-[10px] text-muted-foreground hover:text-primary transition-colors no-underline"
            >
              and {hiddenCount} more on Astro-COLIBRI →
            </a>
          )}
        </div>
      )}

      {/* ── Empty state ─────────────────────────────────────────────────── */}
      {!loading && !error && data?.available === false && (
        <div className="h-28 rounded border border-dashed border-border flex items-center justify-center text-[11px] text-muted-foreground">
          No follow-up reports in Astro-COLIBRI for this event
        </div>
      )}
    </div>
  );
}
